### ISSUE TITLE
Only one device are reflected in the interface

### ISSUE THREAD

**Issue by Horoshist** [sergeylysov/sst_cloud#1]
Привет, Сергей!

Прежде всего: спасибо вам за вашу работу :)

Я установил интеграцию, в целом все выглядит хорошо, но я и обнаружил две проблемы:
1) У меня есть два смарт-устройства neptune в одной учетной записи sst, но я вижу только одно устройство в интерфейсе HA после настройки интеграции. Можно ли добавить поддержку для нескольких устройств? Я думаю, что единственный вариант для меня прямо сейчас - создать вторую учетную запись sst и назначить ей второй нептун.
2) Я не уверен, что делают кнопки "первая группа" и "вторая группа". Если они должны закрывать и открывать клапаны - в моем случае они не работают :(

В целом, я думаю, было бы здорово добавить описание к этой интеграции, например, список доступных функций.

Я еще не проверял счетчики - попробую подключить их к нептуну в течение следующей недели. Также я могу помочь вам с проведением некоторых тестов, если вам это нужно. Ваше здоровье!

С наилучшими пожеланиями

**Comment by sergeylysov** [comment]
Привет! 

Давайте попробуем разобраться и все исправить!
По идее с несколькими устройствами работать должно, но проверить мне было не на чем. Поэтому могут быть проблемы.
1) Во первых подскажите какие именно у вас устройства? я проверял только на Neptun Smart.
2) Про кнопки с названиями групп, это кнопки для перекрывания кранов, в Neptun Smart в двухзонном режиме, видимо из-за различий конфигурации они не работают.
3) Для того чтобы понять почему не раотает у вас, хорошо бы получить конфигурацию ваших устройств, для этого можно авторизоваться на https://web.sst-cloud.com, открыть инструменты разработчика в браузере (обычно F12) выбрать раздел сеть в инструментах разработчика, затем кликнуть на сам дом в интерфейсе сайта, и найти запрос к api.sst-cloud.com/houses/[id дома]/devices открыть ответ на этот запрос и прислать его мне, можно сразу в Telegram https://t.me/s_lysov, чтобы было быстрее.
На скриншоте примерно как это выглядит в браузере.

![изображение](https://user-images.githubusercontent.com/18576858/164207533-1632ad8b-6a8c-419d-b28a-50191eb67a1e.png)

Если возникнут какие то вопросы в процессе получения конфигурации устройств пишите, постараюсь помочь!

**Comment by sergeylysov** [comment]
Исправлено в версии 0.1.1
