### ISSUE TITLE
форма ввода IP адреса шлюза

### ISSUE THREAD

**Issue by latishev** [sergeylysov/sst_cloud#10]
Во время первоначальной настройки и добавлении интеграции SST Cloud Integration всплывает форма ввода IP адреса шлюза, явно это след какой-то другой интеграции. После перезагрузки HA и очередной попытки добавления интеграции выпала форма ввода логина и пароля аккаунта SST Cloud.

Значительное время понадобилось, что бы понять, что для интеграции не требуется локальный IP адрес. Прошу дополнить wiki скриншотом и описанием формы ввода логина и пароля, это позволит распознать, что "что-то пошло не так".

**Comment by sergeylysov** [comment]
Не пойму откуда могла взяться форма воода ip-адреса, вроде нигде ничего подобного нет, добавил скриншот про ввод логина пароля.
