### ISSUE TITLE
при пропадании связи с 1 радиодатчиком LoRa состояние меняется у всех подключенных датчиков

### ISSUE THREAD

**Issue by latishev** [sergeylysov/sst_cloud#11]
При пропадании связи с 1 радиодатчиком LoRa состояние меняется у всех подключенных датчиков.
Entity ID все уникальные, например binary_sensor.wirelessleaksensor_lost_none_5.

Модуль Neptun Smart, версия ПО 1.1.5. Подвязан одновременно к Tuya и SST Cloud, в настоящий момент прописаны 5 датчиков  LoRa.

**Comment by sergeylysov** [comment]
Изменил сверку по имени на всерку по серийному номеру, думаю должно помочь, попробуйте обновиться до 0.1.8 отпишитесь ушла ли проблема.

**Comment by latishev** [comment]
Спасибо за оперативность. Обновился, протестировал бегло, на первый взгляд работает корректно. Через пару дней отпишусь после всеобъемливающих тестов.

**Comment by latishev** [comment]
Работает корректно
