### ISSUE TITLE
Присвоение имен и id сенсоров радиодатчиков LoRa в соответствии с их серийными номерами

### ISSUE THREAD

**Issue by latishev** [sergeylysov/sst_cloud#12]
Прошу рассмотреть возможность при разворачивании интеграции автоматического присвоения наименований сенсорам радиодатчиков LoRa и их id в соответствии с их серийными номерами.

**Comment by sergeylysov** [comment]
Насчет имен не согласен, в имя прописывается имя датчика из SST Cloud, на мой взгляд это позволяет проще идентифицировать датчик, а уникальный ID и так берется из серийного номера
self._attr_unique_id = f"{self._sensor.get_wireless_leak_serial_number}_WireLessLeakSensorAlert"
