### ISSUE TITLE
Доработка для работы с терморегуляторами теплого пола EcoSmart 25

### ISSUE THREAD

**Issue by ABolikov** [sergeylysov/sst_cloud#13]
Добрый день. Спасибо вам за ваши труды !!! Не могли бы сделать доработку для работы с терморегуляторами пола. Таких устройств очень много, это было бы полезно.

**Comment by sergeylysov** [comment]
Добрый день! Доработать можно, но понадобится Ваша помощь. Свяжитесь со мной по Telegram https://t.me/s_lysov
Для доработки понадобится формат в котором приходит описание устройства, можно его получить по инструкции https://github.com/sergeylysov/sst_cloud/issues/2#issuecomment-1111997255
Либо временно передать мне доступ к учетной записи, с привязаным терморегулятором, это бы позволило быстрее отладить интеграцию. (обещаю не менять параметры терморегулятора, по крайней мере без предупреждения). В любом случае свяжитесь через телеграм.

**Comment by sergeylysov** [comment]
Реализовано в версии 0.1.9

**Comment by ABolikov** [comment]
Добрый день.
К сожалению появилась возможность только сейчас поработать по текущему вопросу.
Обновил интеграцию устройства у меня не подтянулись.
Не могу найти ваш контакт для Telegram, готово платно поработать по данному вопросу. Мой телеграм @BolikovAleksey

**Comment by ABolikov** [comment]
Данные по дейвайсам: [{"id":211936,"configuration":"AlRBUgD7VAACISBTAAkBAQYeIwAJACFDAKgAPCEAeAUCHBwCWCEC0CEDDAUEsBwE7CEF3CEGGAUHvBwH+CEIcCEIrAUKUBwKjCELfCELuAUNXBwNmCEOECEOTAUP8BwQLCERHCERWAUS/BwTOCETsCET7AUVkBwVzCEWvCEW+AUYnBwY2CEZUCEZjAUbMBwbbCEcmCEc1AUeeBwetCEfLCEfaAUg0BwhDCEiOCEidAUkGBwkVCEkzCElCAUmcBwmrCFJAAVUNTEyNE0AEUQ4OkEwOjFEOjU2OkY5Ojg4QQABAFoAAQFMAAMF9RVEAAoxNjY5MTUzNzMyVwABBEgAAQE+9w==","parsed_configuration":"{\"chart\": [[60, 33], [120, 5], [540, 28], [600, 33], [720, 33], [780, 5], [1200, 28], [1260, 33], [1500, 33], [1560, 5], [1980, 28], [2040, 33], [2160, 33], [2220, 5], [2640, 28], [2700, 33], [2940, 33], [3000, 5], [3420, 28], [3480, 33], [3600, 33], [3660, 5], [4080, 28], [4140, 33], [4380, 33], [4440, 5], [4860, 28], [4920, 33], [5040, 33], [5100, 5], [5520, 28], [5580, 33], [5820, 33], [5880, 5], [6300, 28], [6360, 33], [6480, 33], [6540, 5], [6960, 28], [7020, 33], [7320, 33], [7380, 5], [7800, 28], [7860, 33], [7980, 33], [8040, 5], [8400, 28], [8460, 33], [8760, 33], [8820, 5], [9240, 28], [9300, 33], [9420, 33], [9480, 5], [9840, 28], [9900, 33]], \"detector\": 1, \"settings\": {\"mode\": \"chart\", \"bright\": 9, \"status\": \"on\", \"sensor_set\": {\"air\": \"unselected\", \"floor\": \"selected\", \"pre_heating\": \"selected\"}, \"temperature_air\": 35, \"curr_temperature\": 33, \"open_window_status\": {\"open_window\": \"unselected\", \"open_window_minutes\": 0}, \"temperature_manual\": 30, \"temperature_correction_air\": 0}, \"device_id\": \"T5124\", \"mac_address\": \"D8:A0:1D:56:F9:88\", \"relay_status\": \"on\", \"signal_level\": 4, \"access_status\": \"available\", \"current_temperature\": {\"temperature_air\": 32, \"temperature_floor\": 33}}","timeout":180,"time_setting":{"id":116304,"workday_time_range":[["06:10:20","11:20:00"],["16:20:00","22:20:00"]],"vacation_time_range":[["06:10:20","11:20:00"],["16:20:00","22:20:00"]],"device":211936},"group":null,"active_network":77810,"specific_settings":{},"created_at":"2022-01-31T18:31:44.338587Z","updated_at":"2022-11-22T15:48:56.227128Z","name":"Пол в ванной","type":6,"previous_mode":"chart","is_active":true,"is_connected":true,"mac_address":"D8:A0:1D:56:F9:88","power":1,"power_relay_time":"91518","chart_temperature_comfort":26,"chart_temperature_economical":18,"wireless_sensors_names":[],"line_names":["line-1","line-2","line-3","line-4"],"lines_enabled":[true,true,true,true],"house":83907},{"id":211944,"configuration":"AlRBUgCbVAACGB1TAAkBAAYZIwAJABxDAEgBpBwB4AwEdBwFKAwHRBwHgAwKFBwKyAwM5BwNIAwPtBwQaAwShBwSwAwVVBwWCAwYJBwYYAwa9BwbqAwdxBwhSAwjZBwm6AxJAAVUNTEyNE0AEUQ4OkEwOjFEOjVCOjFEOjgwQQABAFoAAQFMAAMCOxpEAAoxNjY5MTUzMzIzVwABBEgAAQGbDw==","parsed_configuration":"{\"chart\": [[420, 28], [480, 12], [1140, 28], [1320, 12], [1860, 28], [1920, 12], [2580, 28], [2760, 12], [3300, 28], [3360, 12], [4020, 28], [4200, 12], [4740, 28], [4800, 12], [5460, 28], [5640, 12], [6180, 28], [6240, 12], [6900, 28], [7080, 12], [7620, 28], [8520, 12], [9060, 28], [9960, 12]], \"detector\": 1, \"settings\": {\"mode\": \"manual\", \"bright\": 9, \"status\": \"on\", \"sensor_set\": {\"air\": \"unselected\", \"floor\": \"selected\", \"pre_heating\": \"selected\"}, \"temperature_air\": 35, \"curr_temperature\": 28, \"open_window_status\": {\"open_window\": \"unselected\", \"open_window_minutes\": 0}, \"temperature_manual\": 25, \"temperature_correction_air\": 0}, \"device_id\": \"T5124\", \"mac_address\": \"D8:A0:1D:5B:1D:80\", \"relay_status\": \"on\", \"signal_level\": 4, \"access_status\": \"available\", \"current_temperature\": {\"temperature_air\": 29, \"temperature_floor\": 24}}","timeout":180,"time_setting":{"id":116311,"workday_time_range":[["06:10:20","11:20:00"],["16:20:00","22:20:00"]],"vacation_time_range":[["06:10:20","11:20:00"],["16:20:00","22:20:00"]],"device":211944},"group":null,"active_network":77810,"specific_settings":{},"created_at":"2022-01-31T18:57:52.682597Z","updated_at":"2022-11-22T15:42:04.856965Z","name":"Пол на лоджии","type":6,"previous_mode":"manual","is_active":true,"is_connected":true,"mac_address":"D8:A0:1D:5B:1D:80","power":1,"power_relay_time":"34284","chart_temperature_comfort":26,"chart_temperature_economical":18,"wireless_sensors_names":[],"line_names":["line-1","line-2","line-3","line-4"],"lines_enabled":[true,true,true,true],"house":83907}]

**Comment by ABolikov** [comment]
@sergeylysov Я выше опечатался, не "платно" а ПЛОТНО =) Исправил =)
