### ISSUE TITLE
Счетчики воды недоступны в v0.1.11

### ISSUE THREAD

**Issue by Usever** [sergeylysov/sst_cloud#14]
После обновления на версию v0.1.11 в интеграции пропали счетчики воды:
sensor.watercounter_net
sensor.watercounter_net_2

Home Assistant выдает ошибку "Этот объект больше не предоставляется интеграцией sst_cloud. Вы можете удалить его на вкладке "Настройки", если он больше не будет использоваться.".

При этом новых entity с счетчиками воды не появилось.

**Comment by sergeylysov** [comment]
а в журнале сервера есть какие то ошибки?

**Comment by Usever** [comment]
Нет, все чисто.
При этом, в версии v0.1.10 все работает нормально.

**Comment by Usever** [comment]
Полагаю, проблема в переносе данного блока:

https://github.com/sergeylysov/sst_cloud/blob/cdd23a7929d5656ec1d26b5bc133b3b816cf3d17/custom_components/sst_cloud/s
ensor.py#L32-L33

**Comment by sergeylysov** [comment]
Да, похоже проблема был именно там, спасибо, исправил в v0.1.12
