### ISSUE TITLE
Прошу подсказать как добавить свои устройства

### ISSUE THREAD

**Issue by BaronKorfRus** [sergeylysov/sst_cloud#15]
Как добавить свои устройства, просьба направить что почитать или посмотреть. Интеграцию в НА добавил и подключение в SST Cloud есть, но как добавить свои термостаты? У меня MCS 350, возможно они не поддерживаются текущей интеграцией?

**Comment by sergeylysov** [comment]
Поддержка MCS 350 добавлена в версии v0.1.14
