### ISSUE TITLE
Ошибка при установке терморегулятора в триггер для автоматизации.  

### ISSUE THREAD

**Issue by ABolikov** [sergeylysov/sst_cloud#16]
@sergeylysov Добрый день. Обнаружил ошибку

"Ошибка при установке терморегулятора в триггер для автоматизации."
Устройство: Терморегулятор: EcoSmart 25
Шаги:
 В UI HA перейти на экран создания автоматизации.
 Создать автоматизацию со следующим тригером:
`  - platform: device` 
`     device_id: a5f6c0a4aa063f09f0d984dfe3e9626c` 
`     domain: climate` 
`     entity_id: climate.pol_v_vannoi` 
`     type: hvac_mode_changed` 
При попытке сохранить автоматизацию выводится сообщение:
`Message malformed: required key not provided @ data['to']`

Так же необходимо убрать отладочное сообщение: VALUE. Данное сообщение постоянно пишется в логи системы следующим образом: `2022-12-22 17:26:50.025 WARNING (MainThread) [custom_components.sst_cloud.number] value`

**Comment by ABolikov** [comment]
Также замечена ошибка:
`Уровень: ПРЕДУПРЕЖДЕНИЕ
Logger: homeassistant.components.number
Source: components/number/__init__.py:366
Integration: Число ([documentation](https://www.home-assistant.io/integrations/number), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+number%22))
First occurred: 21:54:47 (1 occurrences)
Last logged: 21:54:47

custom_components.sst_cloud.number::BrightSet is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.`

**Comment by sergeylysov** [comment]
Не воспроизводится в 0.1.15
