### ISSUE TITLE
Терморегулятор OKE-20

### ISSUE THREAD

**Issue by mxsob** [sergeylysov/sst_cloud#17]
Можно ли добавить поддержку терморегулятора OKE-20?
type=5

**Comment by sergeylysov** [comment]
Пришлите полную JSON этого терморегулятора, постараюсь добавить

**Comment by ikorneichuk** [comment]
нужно выцепить из результаты из API SST ? у меня тоже ОКЕ стоят .

**Comment by sergeylysov** [comment]
Да, вот здесь я описывал как это сделать, если будут вопросы пишите в телеграм https://t.me/s_lysov
https://github.com/sergeylysov/sst_cloud/issues/2#issuecomment-1111997255

**Comment by ikorneichuk** [comment]
Ну и вот вроде есть описание всего запроса: 
`HTTP 200 OK
Allow: GET, POST, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "name": "Device List",
    "description": "",
    "renders": [
        "application/json",
        "text/html"
    ],
    "parses": [
        "application/json",
        "application/x-www-form-urlencoded",
        "multipart/form-data"
    ],
    "actions": {
        "POST": {
            "id": {
                "type": "integer",
                "required": false,
                "read_only": true,
                "label": "ID"
            },
            "configuration": {
                "type": "field",
                "required": false,
                "read_only": false,
                "label": "Configuration"
            },
            "parsed_configuration": {
                "type": "field",
                "required": false,
                "read_only": true,
                "label": "Parsed configuration"
            },
            "timeout": {
                "type": "field",
                "required": false,
                "read_only": true,
                "label": "Timeout"
            },
            "time_setting": {
                "type": "nested object",
                "required": false,
                "read_only": false,
                "label": "Time setting",
                "children": {
                    "id": {
                        "type": "integer",
                        "required": false,
                        "read_only": true,
                        "label": "ID"
                    },
                    "workday_time_range": {
                        "type": "list",
                        "required": false,
                        "read_only": false,
                        "label": "Workday time range",
                        "child": {
                            "type": "list",
                            "required": false,
                            "read_only": false,
                            "label": "Workday time range",
                            "child": {
                                "type": "time",
                                "required": false,
                                "read_only": false,
                                "label": "Workday time range"
                            }
                        }
                    },
                    "vacation_time_range": {
                        "type": "list",
                        "required": false,
                        "read_only": false,
                        "label": "Vacation time range",
                        "child": {
                            "type": "list",
                            "required": false,
                            "read_only": false,
                            "label": "Vacation time range",
                            "child": {
                                "type": "time",
                                "required": false,
                                "read_only": false,
                                "label": "Vacation time range"
                            }
                        }
                    },
                    "device": {
                        "type": "field",
                        "required": false,
                        "read_only": true,
                        "label": "Device"
                    }
                }
            },
            "group": {
                "type": "field",
                "required": false,
                "read_only": false,
                "label": "Group"
            },
            "active_network": {
                "type": "field",
                "required": false,
                "read_only": false,
                "label": "Active network"
            },
            "specific_settings": {
                "type": "field",
                "required": false,
                "read_only": false,
                "label": "Specific settings"
            },
            "created_at": {
                "type": "datetime",
                "required": false,
                "read_only": true,
                "label": "Created at"
            },
            "updated_at": {
                "type": "datetime",
                "required": false,
                "read_only": true,
                "label": "Updated at"
            },
            "name": {
                "type": "string",
                "required": false,
                "read_only": false,
                "label": "Name",
                "max_length": 128
            },
            "type": {
                "type": "choice",
                "required": false,
                "read_only": false,
                "label": "Тип устройства",
                "choices": [
                    {
                        "value": 0,
                        "display_name": "mcs300"
                    },
                    {
                        "value": 1,
                        "display_name": "mcs350"
                    },
                    {
                        "value": 2,
                        "display_name": "Neptun"
                    },
                    {
                        "value": 3,
                        "display_name": "Equation"
                    },
                    {
                        "value": 4,
                        "display_name": "Equation ProW+WiFi"
                    },
                    {
                        "value": 5,
                        "display_name": "OK Electro"
                    },
                    {
                        "value": 6,
                        "display_name": "EcoSmart 25"
                    },
                    {
                        "value": 7,
                        "display_name": "Neptun Smart"
                    }
                ]
            },
            "previous_mode": {
                "type": "string",
                "required": false,
                "read_only": false,
                "label": "Previous mode",
                "max_length": 10
            },
            "is_active": {
                "type": "boolean",
                "required": false,
                "read_only": true,
                "label": "Устройство активированно"
            },
            "is_connected": {
                "type": "boolean",
                "required": false,
                "read_only": false,
                "label": "Is connected"
            },
            "mac_address": {
                "type": "string",
                "required": false,
                "read_only": false,
                "label": "Mac address",
                "max_length": 20
            },
            "power": {
                "type": "integer",
                "required": false,
                "read_only": false,
                "label": "Power",
                "min_value": 0,
                "max_value": 2147483647
            },
            "power_relay_time": {
                "type": "string",
                "required": false,
                "read_only": true,
                "label": "Power relay time"
            },
            "chart_temperature_comfort": {
                "type": "integer",
                "required": false,
                "read_only": false,
                "label": "Chart temperature comfort",
                "min_value": -2147483648,
                "max_value": 2147483647
            },
            "chart_temperature_economical": {
                "type": "integer",
                "required": false,
                "read_only": false,
                "label": "Chart temperature economical",
                "min_value": -2147483648,
                "max_value": 2147483647
            },
            "wireless_sensors_names": {
                "type": "list",
                "required": false,
                "read_only": false,
                "label": "Wireless sensors names",
                "child": {
                    "type": "string",
                    "required": false,
                    "read_only": false,
                    "label": "Wireless sensors names",
                    "max_length": 64
                }
            },
            "line_names": {
                "type": "list",
                "required": false,
                "read_only": false,
                "label": "Line names",
                "child": {
                    "type": "string",
                    "required": false,
                    "read_only": false,
                    "label": "Line names",
                    "max_length": 64
                }
            },
            "lines_enabled": {
                "type": "list",
                "required": false,
                "read_only": false,
                "label": "Lines enabled",
                "child": {
                    "type": "boolean",
                    "required": false,
                    "read_only": false,
                    "label": "Lines enabled"
                }
            },
            "house": {
                "type": "field",
                "required": false,
                "read_only": true,
                "label": "Домовладения"
            }
        }
    }
}`

**Comment by sergeylysov** [comment]
Добавлена поддержка в v0.1.22

**Comment by ikorneichuk** [comment]
Отлично все работает. Спасибо.

**Comment by sergeylysov** [comment]
Вроде должно быть устройство терморегулятор

**Comment by mxsob** [comment]
> Отлично все работает. Спасибо. Только вопрос? интеграция только объекты создает. устройства не добавляет? или через HACS это нельзя сделать?

Появляется устройство с моделью "Thermostat Equation", через HACS.

**Comment by sergeylysov** [comment]
Да, похоже такое и создает, просто по функционалу они одинаковые, поэтому сделал на основе Thermostat Equation, по возможности постараюсь поменять название позже.

**Comment by sergeylysov** [comment]
Заведите отдельный issue, чтобы было мне напоминание, а лучше 2, на датчик температуры и на расход энергии, по возможности сделаю
