### ISSUE TITLE
нужна помощь в интеграции с ProW+ WiFi

### ISSUE THREAD

**Issue by Wayler87** [sergeylysov/sst_cloud#2]
Хочу попробовать Вашу интеграцию с ProW+ WiFi, но не совсем понял как добавить интеграцию в НА, прошу помочь.
на данный момент перенес папку sst_cloud в custom components и в файле sst в начале прописал логин с паролем.
почта для обратной связи wayler@yandex.ru
Заранее благодарен, Виктор

**Comment by sergeylysov** [comment]
Проще всего устновить через HACS добавив пользовательский репозито репозиторий, как в инструкции https://hacs.xyz/docs/faq/custom_repositories
В качестве репозитория нужно указать https://github.com/sergeylysov/sst_cloud
Либо просто скопировать папку в custom_components, как вы уже сделали, но никакие файлы редактировать не нужно, после добавления перезагрузить HA, перейти в Конфигурация - Устройства и службы - Добавить интеграцию, в поиске ввести SST (если не находит, нажать Ctrl+F5 - чтобы обновился кэш браузера) и добавить, она спросит логин и пароль от сервиса, после ввода должно найти устройства.
Но есть подозрения, что с ProW+ WiFi может не заработать, т.е. просто не найдет ни одного устройства. Если так и произойдет, пишите, постараюсь поправить, но нужна будет ваша помощь, чтобы собрать техническую информацию.

**Comment by Wayler87** [comment]
Здравствуйте, спасибо за помощь.
К сожалению Вы оказались правы, ни одно устройство не найдено.

**Comment by sergeylysov** [comment]
Для того чтобы понять почему не раотает у вас, хорошо бы получить конфигурацию ваших устройств, для этого можно авторизоваться на https://web.sst-cloud.com/, открыть инструменты разработчика в браузере (обычно F12) выбрать раздел сеть в инструментах разработчика, затем кликнуть на сам дом в интерфейсе сайта, и найти запрос к api.sst-cloud.com/houses/[id дома]/devices открыть ответ на этот запрос и прислать его мне, можно сразу в Telegram https://t.me/s_lysov, чтобы было быстрее.
    На скриншоте примерно как это выглядит в браузере.
![изображение](https://user-images.githubusercontent.com/18576858/165727738-4610893e-141a-43e6-b774-54083cbd2d05.png)

Если возникнут какие то вопросы в процессе получения конфигурации устройств пишите, постараюсь помочь!

**Comment by sergeylysov** [comment]
Исправлено в версии 0.1.4
