### ISSUE TITLE
Добавление счетчиков воды в Энергия

### ISSUE THREAD

**Issue by oneevil** [sergeylysov/sst_cloud#20]
В конфиг энергии счтечики воды не добавляются /config/energy
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by sergeylysov** [comment]
к сожалению HA почему то не видит SensorStateClass.TOTAL видимо поэтому не отображает в энергии.
Есть обходной путь, добавить в configuration.yaml для каждого счетчика:
template:
    - sensor:
      - name: "water counter"
        state: "{{ states('sensor.watercounter') }}"
        unit_of_measurement: m³
        device_class: water
        state_class: total_increasing
Тогда будет еще одно устройство, которое уже можно добавить в энергию

**Comment by oneevil** [comment]
Немного уточню - он не видит SensorDeviceClass.WATER

**Comment by bisquit2003** [comment]
на всякий случай для нубов вроде меня state надо такой, если у вас счетчика и вы хотите общее потребление:
{{ states('sensor.watercounter_provodnaia_liniia_1') | float | round (2) + states('sensor.watercounter_provodnaia_liniia_2') | float | round (2)}}
