### ISSUE TITLE
Фикс открытие и закрытие кранов

### ISSUE THREAD

**Issue by oneevil** [sergeylysov/sst_cloud#21]
Отснифил андройд приложение, запрос методом PATCH в https://api.sst-cloud.com/houses/92529/devices/227687/module_settings/

Открытие кранов:
`{"module_config":{"first_group_valves_state":"opened","second_group_valves_state":"opened"}}`

Закрытие кранов:
`{"module_config":{"first_group_valves_state":"closed","second_group_valves_state":"closed"}}`

При передаче только этих параметров краны приходят в движение.
А в приложении он там шлет еще кучу всего лишнего.
Предыдущий вариант плох тем что при открытии/закрытии кранов может изменится статус мойки полов, блокировки кнопок и действия при потери сигнала датчика.

**Comment by sergeylysov** [comment]
переделал в v0.1.18  проверьте

**Comment by oneevil** [comment]
Да все работает.
