### ISSUE TITLE
Problem with adding second Neptune sensors

### ISSUE THREAD

**Issue by TolianIPB** [sergeylysov/sst_cloud#24]
Если подключить два Нептуна, то у HA не получается добавить сенсоры двух зон второго устройства.

If you connect two Neptunes, then HA cannot add sensors for two zones of the second device.

```
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:540
Integration: Бинарный сенсор (documentation, issues)
First occurred: 13:42:04 (2 occurrences)
Last logged: 13:42:04

Platform sst_cloud does not generate unique IDs. ID first_group_alarm_module_alert already exists - ignoring binary_sensor.alert_module_first_group_alarm
Platform sst_cloud does not generate unique IDs. ID second_group_alarm_module_alert already exists - ignoring binary_sensor.alert_module_second_group_alarm
```

**Comment by sergeylysov** [comment]
Опубликовал  v0.1.19  с исправлениями, просьба проверить

**Comment by TolianIPB** [comment]
Сергей, большое спасибо! Всё теперь отлично!

Sergey, thank you very much! Everything is great now!

![nep](https://user-images.githubusercontent.com/36660653/224339849-9bda71d7-f939-43bc-b135-6e30c7f235d2.jpg)

**Comment by sergeylysov** [comment]
Исправлено в  v0.1.19
