### ISSUE TITLE
Пропали сенсоры

### ISSUE THREAD

**Issue by MrKuskov** [sergeylysov/sst_cloud#25]
Доброе время суток. После обновления v0.1.22 отвалились сенсоры температуры теплого пола и воздуха. Датчик теплого пола "Equation", в SST Cloud данные есть. В НА пишет:

> Этот объект больше не предоставляется интеграцией sst_cloud. Вы можете удалить его на вкладке "Настройки", если он больше не будет использоваться.

Хорошо, сенсор температуры пола можно вытащить через атрибуты

> sensor:
>   platform: template
>     - name: "floor temp"
>     value_template: "{{ state_attr('climate.vanna',"current_temperature") }}"
>     unit_of_measurement: C
>     device_class: temperature
> 

А где взять сенсор температуры воздуха?

Откатился на версию 0.1.21 - датчиков нет, 0.1.20 - датчики появились. AirThemperatureSensor и FloorThemperatureSensor

**Comment by DrWhiteMan** [comment]
Доброго дня. Во первых спасибо автору за интеграцию с терморегулятором Equation, очень ее ждал.
А что касается проблемы описанной выше, то подтверждаю ее наличие на v0.1.22. Подскажите, как откатиться на 0.1.20 без отката всего HA и удаления настроенной интеграции?

**Comment by DrWhiteMan** [comment]
Нашел только вот такое:
Logger: homeassistant.components.sensor
Source: custom_components/sst_cloud/sensor.py:116
Integration: Сенсор (documentation, issues)
First occurred: 17 марта 2023 г. в 16:50:44 (1 occurrences)
Last logged: 17 марта 2023 г. в 16:50:44

Error while setting up sst_cloud platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/sst_cloud/sensor.py", line 29, in async_setup_entry
    new_devices.append(AirThemperatureSensor(module))
  File "/config/custom_components/sst_cloud/sensor.py", line 116, in __init__
    self._state = self._module.get_current_air_temperature
AttributeError: 'ThermostatEquation' object has no attribute 'get_current_air_temperature'

**Comment by MrKuskov** [comment]
> Подскажите, как откатиться на 0.1.20 без отката всего HA и удаления настроенной интеграции?

через HACS повторно скачиваете выбрав нужную версию, затем перезагрузка и после игнорирование обновления.

**Comment by sergeylysov** [comment]
Опубликовал 0.1.23 проверьте пожалуйста

**Comment by MrKuskov** [comment]
> Опубликовал 0.1.23 проверьте пожалуйста

Все работает. Отлично. Спасибо за интеграцию. Единственное, что термостат создался заново под номером 2. Пришлось удалить и заново создать интеграцию, что бы карточку не править.

**Comment by sergeylysov** [comment]
Да, создаться заново мог, потому что я изменил имена терморегулятора, в зависимости от модели
