### ISSUE TITLE
Перестали работать терморегуляторы теплого пола EcoSmart 25

### ISSUE THREAD

**Issue by ABolikov** [sergeylysov/sst_cloud#28]
Сергей, добрый день. 
Перестали работать терморегуляторы теплого пола EcoSmart 25.
На текущий момент, включить\отключить и изменить температура на терморегуляторе нет возможности.
Ничего не происходит при выполнении подобный действий.

Версия HA:
Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1

В журнал есть следующие сообщения:

Уровень: ПРЕДУПРЕЖДЕНИЕ
Эта ошибка возникла в кастомной интеграции.
===========================
Logger: custom_components.sst_cloud.climate
Source: custom_components/sst_cloud/climate.py:77
Integration: SST Cloud integration ([documentation](https://github.com/sergeylysov/sst_cloud), [issues](https://github.com/sergeylysov/sst_cloud/issues))
First occurred: 22:44:54 (1 occurrences)
Last logged: 22:44:54

switchOn heat
===========================

Уровень: ПРЕДУПРЕЖДЕНИЕ
Эта ошибка возникла в кастомной интеграции.
Logger: custom_components.sst_cloud.climate
Source: custom_components/sst_cloud/climate.py:69
Integration: SST Cloud integration ([documentation](https://github.com/sergeylysov/sst_cloud), [issues](https://github.com/sergeylysov/sst_cloud/issues))
First occurred: 22:44:48 (1 occurrences)
Last logged: 22:44:48

set_hvac_mode heat
============================

**Comment by sergeylysov** [comment]
Не воспроизводится
