### ISSUE TITLE
Поддержка терморегуляторов MCS300

### ISSUE THREAD

**Issue by rrmt23** [sergeylysov/sst_cloud#29]
Здравствуйте!

Планируется ли поддержка MCS300?

Спасибо!

**Comment by sergeylysov** [comment]
Пришлите json-описание терморегулятора, постараюсь добавить, как его найти описывал здесь https://github.com/sergeylysov/sst_cloud/issues/2#issuecomment-1111997255

**Comment by rrmt23** [comment]
> Пришлите json-описание терморегулятора, постараюсь добавить, как его найти описывал здесь [#2 (comment)](https://github.com/sergeylysov/sst_cloud/issues/2#issuecomment-1111997255)

к сожалению не нашел куда вам отправить.

**Comment by sergeylysov** [comment]
Можно прям сюда, либо в телегу https://t.me/s_lysov

**Comment by sergeylysov** [comment]
Реализовано в v0.1.28
