### ISSUE TITLE
Установка и общие вопросы

### ISSUE THREAD

**Issue by bisquit2003** [sergeylysov/sst_cloud#3]
Здравствуйте, простите за глупые вопросы:
Ставить как?
Работа облачная?
Не начинает ли отваливаться prow+Wi-Fi от Wi-Fi сети? Я пробовал локальную интеграцию другого разработчика (https://github.com/allovaro/neptun_homeassistant)- модуль начал отваливался от роутера каждую минуту, отправил в сервис, не понятно, проблема по железу или из-за интеграции. В сервисе же сказали что нужно порты на роутере открыть, но какие не сказали. Техподдержка подтвердила - портов много, но назвали только один 35768

**Comment by sergeylysov** [comment]
Добрый день! Описал установку в файле README.md, так же дублирую ниже.
Работа именно облачная, т.е. компонент обращается к облаку SST Cloud, судя по вашему описанию у вас используется старая прошивка нептуна с локальным доступом, поэтому эта интеграция не подойдет. Можно обновиться до прошивки в которой используется облако (не уверен что это возможно, но у меня был prow+Wi-Fi который я обновлял) но при этом  его работа будет зависеть от интернета.

## Вариант 1 - черезе HACS
1) Добавить репозиторий https://github.com/sergeylysov/sst_cloud/ в HACS. Перейти в HACS -> Интеграции -> Спарва сверху 3 точки -> Пользовательские репозитории, вставить ссылку и выбрать категорию "Интеграция" -> Добавить.
2) Перезагрузить HA.
3) Настроить интеграцию - Конфигурация -> Устройства и службы -> Добавить интеграцию, в поиске ввести SST, выбрать интеграцию "SST Cloud Integration"


![изображение](https://user-images.githubusercontent.com/18576858/166641784-4cb8b22b-7789-4bc6-942e-467077b82e06.png)

(Если такая интеграция не находится, Ctrl + F5, чтобы обновить кэш браузера)
Ввести логин и пароль.

## Вариант 2 - Вручную
1) Cкопировать каталог sst_cloud из репозитория в папку custom_components на сервере Home Assistant
2)Перезагрузить HA.
3) Настроить интеграцию - Конфигурация -> Устройства и службы -> Добавить интеграцию, в поиске ввести SST, выбрать интеграцию "SST Cloud Integration"


![изображение](https://user-images.githubusercontent.com/18576858/166641784-4cb8b22b-7789-4bc6-942e-467077b82e06.png)

(Если такая интеграция не находится, Ctrl + F5, чтобы обновить кэш браузера)
Ввести логин и пароль.

**Comment by sergeylysov** [comment]
Видел что они предлагали модули туя для Neptun Smart, но что то они пропали из продажи, да и цена у них, мягко говоря, перебор была, особенно для вынужденной меры. Именно про закрытие слышц первый раз. Если они свое облако закроют, будет конечно не очень. Надеюсь хоть тогда выпустят прошивку для локальной работы с модулем.
