### ISSUE TITLE
Иногда счетчики падают в 0

### ISSUE THREAD

**Issue by Professor338** [sergeylysov/sst_cloud#31]
Доброго времени суток.
Иногда почему то счётчики показывают нулевое значение, проблема проявляется где-то раз в неделю, скриншот прикрепил
На сколько заметил падение всегда именно в 0 может как то отфильтровать значение 
![1233ССС](https://github.com/sergeylysov/sst_cloud/assets/115339162/30e62c8f-9eb4-4af0-8195-6da5b489f848)

PS: на вкладку энергия можно так же через раздел customize configuration.yaml повесить свойство total_increasing
    customize:
        sensor.watercounter_net:
            state_class: total_increasing
        sensor.watercounter_net_2:
            state_class: total_increasing

**Comment by sergeylysov** [comment]
В v0.1.26 добавил фильтрацию нулевых значений
