### ISSUE TITLE
Интеграция перестала работать (( 

### ISSUE THREAD

**Issue by IncognitoMSK** [sergeylysov/sst_cloud#33]
Приложение работает может API поменялось ?

**Comment by sergeylysov** [comment]
API не работает, SSL сертификат просрочен https://web.sst-cloud.com, и уже третий день они не могут это исправить, в поддержку написал, но нгнорируют. Веб интерфейс не работает, приложение у меня тоже не работает, не очень понимаю как у вас работает. Если есть возможность напишите в поддержку тоже +7 903 666-11-28 Whatsapp или звонок

**Comment by sergeylysov** [comment]
Техподдержка ответила с 10 раза, обещают сделать до четверга включительно. Поразительно долго для смены сертификата конечно, но я ничего сделать не могу.
