### ISSUE TITLE
HAOS 23-10-04 + sst cloud

### ISSUE THREAD

**Issue by bisquit2003** [sergeylysov/sst_cloud#36]
приветствую, Сергей.
не пойму, так совпало, или в версии хаос 10,04 интеграция сломалась?
бонусом у меня и в родном приложении неактивен стал девайс, поэтому сомнения насчет обновления ха...

**Comment by sergeylysov** [comment]
HA не виноват, да и интеграция тоже, sst-cloud опять отвалился, а ребята не торопятся его ремонтировать.

> Здравствуйте.В данный момент на сервере SSTCLOUD ведутся технические работы.Пожалуйста, не удаляйте устройства, не выходите из аккаунта, не пытайтесь восстановить пароль.По завершении работ работоспособность всех ваших приборов полностью восстановится.Обладатели систем НЕПТУН SMART (с голубыми светодиодами), могут воспользоваться сервисом Smart Life.Подробная информация на сайте

**Comment by bisquit2003** [comment]
> HA не виноват, да и интеграция тоже, sst-cloud опять отвалился, а ребята не торопятся его ремонтировать.

а да, никогда не замечал) спасибо, тогда можно закрывать)

**Comment by sergeylysov** [comment]
SST-cloud подняли, все заработало
