### ISSUE TITLE
Некорректное отображение текущей температуры EcoSmart 25

### ISSUE THREAD

**Issue by megamaska** [sergeylysov/sst_cloud#38]
Сергей, добрый день!
Вначале я бы хотел поблагодарить вас за интеграцию!
Помогите разобраться - у меня 6 термостатов EcoSmart 25,  из них 3 для тёплого пола и 3 для управления батареями.
В НА текущая температура у всех отображается по датчику пола. Как можно поменять на показания с датчика t воздуха?
(на тех, что управляют батареями я подключил датчики пола и спрятал их под рамку, но видимо от нагрева самого термостата, температура сильно завышена)

**Comment by sergeylysov** [comment]
Добрый день! А сам термостат ориентируется на какую температуру? пола или воздуха? или это настраивается?

**Comment by megamaska** [comment]
На термостате можно настроить по какой температуре он ориентируется. У меня термостаты которые управляют теплым полом настроены по датчику пола, а те которые для управления батареями по датчику воздуха.

**Comment by sergeylysov** [comment]
Нужна конфигурация устройства с настройками по датчику пола и с настройками по датчику воздуха, как их получить, описывал [здесь](https://github.com/sergeylysov/sst_cloud/issues/2#issuecomment-1111997255)
Думаю можно будет добавить переключатель для этой настройки.

**Comment by megamaska** [comment]
<img width="1314" alt="GH" src="https://github.com/sergeylysov/sst_cloud/assets/153757921/c6eff4e3-9ad8-4a1b-bbbe-b81dfe0be3e7">

**Comment by sergeylysov** [comment]
другой запрос нужен devices/ он там чуть ниже

**Comment by sergeylysov** [comment]
@megamaska нашел каким методом это делается, думаю можно будет сделать отдельный список для выбора источника температуры, но нужны примеры конфигурации с разными датчиками

**Comment by megamaska** [comment]
Добрый день!
Немного закидали работой)
Этот работает по датчику пола:
{
        "id": 290503,
        "parsed_configuration": "{\"chart\": [[270, 24], [300, 20], [465, 24], [540, 20], [1898, 26], [2010, 20], [3345, 24], [3451, 20], [4785, 24], [4891, 20], [6225, 24], [6331, 20], [7470, 24], [7500, 20], [7665, 24], [7740, 20], [8910, 24], [8940, 20], [9105, 24], [9180, 20]], \"detector\": 1, \"settings\": {\"mode\": \"manual\", \"bright\": 6, \"status\": \"on\", \"sensor_set\": {\"air\": \"unselected\", \"floor\": \"selected\", \"pre_heating\": \"unselected\"}, \"temperature_air\": 35, \"curr_temperature\": 20, \"open_window_status\": {\"open_window\": \"unselected\", \"open_window_minutes\": 0}, \"temperature_manual\": 20, \"temperature_correction_air\": 0}, \"device_id\": \"T5124\", \"mac_address\": \"D5:A0:1D:5E:63:7B\", \"relay_status\": \"off\", \"signal_level\": 4, \"access_status\": \"available\", \"current_temperature\": {\"temperature_air\": 26, \"temperature_floor\": 24}}",
        "timeout": 180,
        "time_setting": {
            "id": 115024,
            "workday_time_range": [
                [
                    "00:00:00",
                    "23:00:00"
                ]
            ],
            "vacation_time_range": [
                [
                    "00:00:00",
                    "23:00:00"
                ]
            ],
            "device": 290503
        },
        "group": null,
        "active_network": 64547,
        "specific_settings": {},
        "created_at": "2022-01-11T11:19:17.441905Z",
        "updated_at": "2024-01-24T16:41:07.371682Z",
        "name": "Душевая (тёплый пол)",
        "type": 6,
        "previous_mode": "manual",
        "is_active": true,
        "is_connected": true,
        "mac_address": "D5:A0:1D:5E:63:7B",
        "power": 180,
        "power_relay_time": "19093",
        "chart_temperature_comfort": 29,
        "chart_temperature_economical": 28,
        "wireless_sensors_names": [],
        "line_names": [
            "line-1",
            "line-2",
            "line-3",
            "line-4"
        ],
        "lines_enabled": [
            true,
            true,
            true,
            true
        ],
        "house": 75341
    },

**Comment by megamaska** [comment]
а этот по датчику воздуха:
 {
        "id": 290519,
        "parsed_configuration": "{\"chart\": [[540, 24], [1380, 20], [1980, 24], [2820, 20], [3420, 24], [4260, 20], [4860, 24], [5700, 20], [6300, 24], [7140, 21], [7740, 24], [8580, 20], [9180, 24], [10020, 20]], \"detector\": 1, \"settings\": {\"mode\": \"manual\", \"bright\": 5, \"status\": \"on\", \"sensor_set\": {\"air\": \"selected\", \"floor\": \"unselected\", \"pre_heating\": \"selected\"}, \"temperature_air\": 35, \"curr_temperature\": 24, \"open_window_status\": {\"open_window\": \"unselected\", \"open_window_minutes\": 0}, \"temperature_manual\": 22, \"temperature_correction_air\": -3}, \"device_id\": \"T5124\", \"mac_address\": \"D7:A0:1D:5E:60:70\", \"relay_status\": \"off\", \"signal_level\": 4, \"access_status\": \"available\", \"current_temperature\": {\"temperature_air\": 23, \"temperature_floor\": 26}}",
        "timeout": 180,
        "time_setting": {
            "id": 117029,
            "workday_time_range": [
                [
                    "00:00:00",
                    "23:00:00"
                ]
            ],
            "vacation_time_range": [
                [
                    "00:00:00",
                    "23:00:00"
                ]
            ],
            "device": 290519
        },
        "group": null,
        "active_network": 64547,
        "specific_settings": {},
        "created_at": "2022-01-11T13:51:18.237022Z",
        "updated_at": "2024-01-24T16:39:18.850178Z",
        "name": "Детская",
        "type": 6,
        "previous_mode": "manual",
        "is_active": true,
        "is_connected": true,
        "mac_address": "D7:A0:1D:5E:60:70",
        "power": 1,
        "power_relay_time": "277599",
        "chart_temperature_comfort": 29,
        "chart_temperature_economical": 28,
        "wireless_sensors_names": [],
        "line_names": [
            "line-1",
            "line-2",
            "line-3",
            "line-4"
        ],
        "lines_enabled": [
            true,
            true,
            true,
            true
        ],
        "house": 75341
    },

**Comment by sergeylysov** [comment]
Спасибо, вроде все есть, в ближайшие дни попробую заняться, там есть еще какой то параметр  "pre_heating": "selected", не знаете что это? в первом не выбран, во втором выбран

**Comment by sergeylysov** [comment]
Опубликовал v0.1.31, попробуйте, должна отображаться температура в зависимости от выбранного датчика, настройку датчика источника можно тоже вывести, но пока этого не делал.

**Comment by sergeylysov** [comment]
Исправлено в  v0.1.31
