### ISSUE TITLE
Сервис sstcloud.ru умер, теперь они работают через сервис atlasiot.ru

### ISSUE THREAD

**Issue by Hitmandc** [sergeylysov/sst_cloud#41]
Сервис sstcloud.ru умер, теперь они работают через сервис https://atlasiot.ru/ в связи с этим оборудование перестало работать в HA. Кто-то сталкивался, получалось ли решить проблему?

**Comment by klim123123** [comment]
Если не регистрироваться в atlasiot и не переводить свои устройства туда, пока работает sstcloud.ru
Если уже сделали такую ошибку, то назад пути нет(по словам поддержки atlasiot)
У меня atlasiot до жути глючит(удалился мой аккаунт, показывается что ус-во офлайн).

**Comment by sergeylysov** [comment]
Подтверждаю, sstcloud работает, если не переводить устройства а атлас, по поводу атласа ничего сказать не могу, не пробовал, но учитывая что они даже видео демонстрационные не смогли записать без ошибок его работы, доверия не внушает, может допилят позже, до адекватного состояния. На сайте атласа не нашел информации о  публичном API, если его не будет будет обидно, так же нет обещаний интеграций в HA.
