### ISSUE TITLE
поймал баг

### ISSUE THREAD

**Issue by bisquit2003** [sergeylysov/sst_cloud#7]
здравствуйте
Поймал интересный баг, устранение на Ваше усмотрение (хотя может и я что-то неправильно делаю, что вероятнее).
Я большую часть сущностей прокидываю из ha в apple homekit
так вот, если ради украшения я прописываю в конфиге:
homekit:
  entity_config:
    switch.waterswitch:
      type: valve
то у меня крашится почти весь хомкит в айфончике, многие устройства становятся недоступными,а как только удаляю - все ок
как выключатель все работает штатно

скрины конфига прилагаю

![image](https://user-images.githubusercontent.com/98059406/168257629-90cb6c72-4f67-4b12-8df7-f94fe542dcb2.png)

![image](https://user-images.githubusercontent.com/98059406/168257457-7d4525ee-159e-4ad1-9fbc-19dd0d6ef074.png)

**Comment by sergeylysov** [comment]
Честно сказать никогда не сталкивался с интеграцией в Homekit, как мне кажется если в HA работает нормально, тут уже вопрос интеграции HA и Homekit. Посмотрите в логи HA, может там какие то ошибки есть?

**Comment by bisquit2003** [comment]
> Честно сказать никогда не сталкивался с интеграцией в Homekit, как мне кажется если в HA работает нормально, тут уже вопрос интеграции HA и Homekit. Посмотрите в логи HA, может там какие то ошибки есть?

не, там по этому поводу тишина.
заметил что это не работает ни с чем, поэтому ошибка, очевидно в ха. спасибо

**Comment by bisquit2003** [comment]
на всякий случай отпишусь, ошибка была моя, необходимо внимательней читать документацию)
при изменении типа устройства в хк его необходимо удалить и добавить заново
